[theme]
base="dark"
primaryColor="#FF00FF"
backgroundColor="#0e0018"
secondaryBackgroundColor="#1f0030"
textColor="#00FFFF"
font="sans serif"

[server]
headless = true
enableCORS=true
enableXsrfProtection=true
